Automatically add dependencies for legacy modules
contao/manager-plugin pull request #2
Opened 2017-01-31 10:13 UTC by aschempp

If a module in `system/modules` does currently not have an `autoload.ini`, the sorting of dependencies gets wrong because the original core modules no longer exist so the sort-by-name no longer applies.

This PR restores at least the functionality to request sorting before the legacy core modules. Having an `autoload.ini` would automatically override these defaults.

*Open question:*
If the legacy modules in `Contao\ModuleLoader` would be a constant instead of a private method, we would not have to re-define these again in the `ModuleConfig`. I suggest to make that change, it cannot be a BC break.

2017-01-31 10:22 UTC, Toflar requested changes
Tests missing to check if a bundle is really loaded after the legacy modules.

2017-01-31 10:23 UTC, Toflar commented
> If the legacy modules in Contao\ModuleLoader would be a constant instead of a private method, we would not have to re-define these again in the ModuleConfig. I suggest to make that change, it cannot be a BC break.

I don't think that's needed here, really. It's something that's never gonna change so it's not needed to be fetched "dynamically". Just leave it as is, imho.

2017-01-31 13:08 UTC, leofeyer commented
>> If the legacy modules in Contao\ModuleLoader would be a constant instead of a private method, we would not have to re-define these again in the ModuleConfig. I suggest to make that change, it cannot be a BC break.
> 
> I don't think that's needed here, really. It's something that's never gonna change so it's not needed to be fetched "dynamically". Just leave it as is, imho.

I don't care either way. I think @Toflar is right though.

2017-01-31 13:23 UTC, aschempp commented
fine with me :-)

2017-01-31 13:24 UTC, Toflar approved these changes

2017-01-31 16:22 UTC, discordier approved these changes

2017-01-31 20:43 UTC, ausi approved these changes

2017-02-01 16:08 UTC, leofeyer approved these changes

2017-02-01 17:11 UTC, merged