Autoload the App namespace if none is configured
contao/manager-plugin pull request #22
Opened 2020-01-08 18:07 UTC by aschempp

With this change, we can remove https://github.com/contao/managed-edition/blob/master/composer.json#L35-L39

We could even make this more universal and use the plugin to set the asset path etc, so the default composer.json gets even smaller 😎

2020-01-08 18:41 UTC, Toflar requested changes
Needs tests but 👍

2020-01-09 09:40 UTC, leofeyer commented
As I have stated in https://github.com/contao/contao/pull/1165, I do not think that we should add any autoloading magic and stick to the Composer defaults instead.

2020-01-18 13:15 UTC, aschempp commented
as https://github.com/contao/contao/pull/1165 has been merged, I think we can merge this too?

2020-01-18 13:28 UTC, Toflar approved these changes
Doesn‘t harm at all and brings us flexibility👍

2020-01-18 13:32 UTC, leofeyer approved these changes

2020-01-18 13:34 UTC, leofeyer commented
I have removed the "autoload" section from the `composer.json` file of the Managed Edition in contao/managed-edition@6b6a70cd89ff732e56dc9e71685d18fc71b36f48.

2020-01-24 18:14 UTC, merged